namespace DaemonMC.Blocks
{
    public static class BlockStates
    {
        public static readonly Dictionary<string, object[]> States = new()
        {
            { "active", new object[] { (byte)0, (byte)1 } },
            { "age", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "age_bit", new object[] { (byte)0, (byte)1 } },
            { "allow_underwater_bit", new object[] { (byte)0, (byte)1 } },
            { "attached_bit", new object[] { (byte)0, (byte)1 } },
            { "attachment", new object[] { "standing", "hanging", "side", "multiple" } },
            { "bamboo_leaf_size", new object[] { "no_leaves", "small_leaves", "large_leaves" } },
            { "bamboo_stalk_thickness", new object[] { "thin", "thick" } },
            { "big_dripleaf_head", new object[] { (byte)0, (byte)1 } },
            { "big_dripleaf_tilt", new object[] { "none", "unstable", "partial_tilt", "full_tilt" } },
            { "bite_counter", new object[] { 0, 1, 2, 3, 4, 5, 6 } },
            { "block_light_level", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "bloom", new object[] { (byte)0, (byte)1 } },
            { "books_stored", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63 } },
            { "brewing_stand_slot_a_bit", new object[] { (byte)0, (byte)1 } },
            { "brewing_stand_slot_b_bit", new object[] { (byte)0, (byte)1 } },
            { "brewing_stand_slot_c_bit", new object[] { (byte)0, (byte)1 } },
            { "brushed_progress", new object[] { 0, 1, 2, 3 } },
            { "button_pressed_bit", new object[] { (byte)0, (byte)1 } },
            { "can_summon", new object[] { (byte)0, (byte)1 } },
            { "candles", new object[] { 0, 1, 2, 3 } },
            { "cauldron_liquid", new object[] { "water", "lava", "powder_snow" } },
            { "chemistry_table_type", new object[] { "compound_creator", "material_reducer", "element_constructor", "lab_table" } },
            { "chisel_type", new object[] { "default", "chiseled", "lines", "smooth" } },
            { "cluster_count", new object[] { 0, 1, 2, 3 } },
            { "color", new object[] { "white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "silver", "cyan", "purple", "blue", "brown", "green", "red", "black" } },
            { "color_bit", new object[] { (byte)0, (byte)1 } },
            { "composter_fill_level", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8 } },
            { "conditional_bit", new object[] { (byte)0, (byte)1 } },
            { "coral_color", new object[] { "blue", "pink", "purple", "red", "yellow" } },
            { "coral_direction", new object[] { 0, 1, 2, 3 } },
            { "coral_fan_direction", new object[] { 0, 1 } },
            { "coral_hang_type_bit", new object[] { (byte)0, (byte)1 } },
            { "covered_bit", new object[] { (byte)0, (byte)1 } },
            { "cracked_state", new object[] { "no_cracks", "cracked", "max_cracked" } },
            { "crafting", new object[] { (byte)0, (byte)1 } },
            { "creaking_heart_state", new object[] { "uprooted", "dormant", "awake" } },
            { "damage", new object[] { "undamaged", "slightly_damaged", "very_damaged", "broken" } },
            { "dead_bit", new object[] { (byte)0, (byte)1 } },
            { "deprecated", new object[] { 0, 1, 2, 3 } },
            { "direction", new object[] { 0, 1, 2, 3 } },
            { "dirt_type", new object[] { "normal", "coarse" } },
            { "disarmed_bit", new object[] { (byte)0, (byte)1 } },
            { "door_hinge_bit", new object[] { (byte)0, (byte)1 } },
            { "double_plant_type", new object[] { "sunflower", "syringa", "grass", "fern", "rose", "paeonia" } },
            { "drag_down", new object[] { (byte)0, (byte)1 } },
            { "dripstone_thickness", new object[] { "tip", "frustum", "middle", "base", "merge" } },
            { "end_portal_eye_bit", new object[] { (byte)0, (byte)1 } },
            { "explode_bit", new object[] { (byte)0, (byte)1 } },
            { "extinguished", new object[] { (byte)0, (byte)1 } },
            { "facing_direction", new object[] { 0, 1, 2, 3, 4, 5 } },
            { "fill_level", new object[] { 0, 1, 2, 3, 4, 5, 6 } },
            { "flower_type", new object[] { "poppy", "orchid", "allium", "houstonia", "tulip_red", "tulip_orange", "tulip_white", "tulip_pink", "oxeye", "cornflower", "lily_of_the_valley" } },
            { "ground_sign_direction", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "growing_plant_age", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 } },
            { "growth", new object[] { 0, 1, 2, 3, 4, 5, 6, 7 } },
            { "hanging", new object[] { (byte)0, (byte)1 } },
            { "head_piece_bit", new object[] { (byte)0, (byte)1 } },
            { "height", new object[] { 0, 1, 2, 3, 4, 5, 6, 7 } },
            { "honey_level", new object[] { 0, 1, 2, 3, 4, 5 } },
            { "huge_mushroom_bits", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "in_wall_bit", new object[] { (byte)0, (byte)1 } },
            { "infiniburn_bit", new object[] { (byte)0, (byte)1 } },
            { "item_frame_map_bit", new object[] { (byte)0, (byte)1 } },
            { "item_frame_photo_bit", new object[] { (byte)0, (byte)1 } },
            { "kelp_age", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 } },
            { "lever_direction", new object[] { "down_east_west", "east", "west", "south", "north", "up_north_south", "up_east_west", "down_north_south" } },
            { "liquid_depth", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "lit", new object[] { (byte)0, (byte)1 } },
            { "minecraft:block_face", new object[] { "down", "up", "north", "south", "west", "east" } },
            { "minecraft:cardinal_direction", new object[] { "south", "west", "north", "east" } },
            { "minecraft:facing_direction", new object[] { "down", "up", "north", "south", "west", "east" } },
            { "minecraft:vertical_half", new object[] { "bottom", "top" } },
            { "moisturized_amount", new object[] { 0, 1, 2, 3, 4, 5, 6, 7 } },
            { "monster_egg_stone_type", new object[] { "stone", "cobblestone", "stone_brick", "mossy_stone_brick", "cracked_stone_brick", "chiseled_stone_brick" } },
            { "multi_face_direction_bits", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63 } },
            { "natural", new object[] { (byte)0, (byte)1 } },
            { "new_leaf_type", new object[] { "acacia", "dark_oak" } },
            { "new_log_type", new object[] { "acacia", "dark_oak" } },
            { "no_drop_bit", new object[] { (byte)0, (byte)1 } },
            { "occupied_bit", new object[] { (byte)0, (byte)1 } },
            { "old_leaf_type", new object[] { "oak", "spruce", "birch", "jungle" } },
            { "old_log_type", new object[] { "oak", "spruce", "birch", "jungle" } },
            { "ominous", new object[] { (byte)0, (byte)1 } },
            { "open_bit", new object[] { (byte)0, (byte)1 } },
            { "orientation", new object[] { "down_east", "down_north", "down_south", "down_west", "up_east", "up_north", "up_south", "up_west", "west_up", "east_up", "north_up", "south_up" } },
            { "output_lit_bit", new object[] { (byte)0, (byte)1 } },
            { "output_subtract_bit", new object[] { (byte)0, (byte)1 } },
            { "pale_moss_carpet_side_east", new object[] { "none", "short", "tall" } },
            { "pale_moss_carpet_side_north", new object[] { "none", "short", "tall" } },
            { "pale_moss_carpet_side_south", new object[] { "none", "short", "tall" } },
            { "pale_moss_carpet_side_west", new object[] { "none", "short", "tall" } },
            { "persistent_bit", new object[] { (byte)0, (byte)1 } },
            { "pillar_axis", new object[] { "y", "x", "z" } },
            { "portal_axis", new object[] { "unknown", "x", "z" } },
            { "powered_bit", new object[] { (byte)0, (byte)1 } },
            { "prismarine_block_type", new object[] { "default", "dark", "bricks" } },
            { "propagule_stage", new object[] { 0, 1, 2, 3, 4 } },
            { "rail_data_bit", new object[] { (byte)0, (byte)1 } },
            { "rail_direction", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 } },
            { "redstone_signal", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "rehydration_level", new object[] { 0, 1, 2, 3 } },
            { "repeater_delay", new object[] { 0, 1, 2, 3 } },
            { "respawn_anchor_charge", new object[] { 0, 1, 2, 3, 4 } },
            { "rotation", new object[] { 0, 1, 2, 3 } },
            { "sand_stone_type", new object[] { "default", "heiroglyphs", "cut", "smooth" } },
            { "sand_type", new object[] { "normal", "red" } },
            { "sapling_type", new object[] { "oak", "spruce", "birch", "jungle", "acacia", "dark_oak", "pale_oak" } },
            { "sculk_sensor_phase", new object[] { 0, 1, 2 } },
            { "sea_grass_type", new object[] { "default", "double_top", "double_bot" } },
            { "sponge_type", new object[] { "dry", "wet" } },
            { "stability", new object[] { 0, 1, 2, 3, 4, 5, 6, 7 } },
            { "stability_check", new object[] { (byte)0, (byte)1 } },
            { "stone_brick_type", new object[] { "default", "mossy", "cracked", "chiseled", "smooth" } },
            { "stone_slab_type", new object[] { "smooth_stone", "sandstone", "wood", "cobblestone", "brick", "stone_brick", "quartz", "nether_brick" } },
            { "stone_slab_type_2", new object[] { "red_sandstone", "purpur", "prismarine_rough", "prismarine_dark", "prismarine_brick", "mossy_cobblestone", "smooth_sandstone", "red_nether_brick" } },
            { "stone_slab_type_3", new object[] { "end_stone_brick", "smooth_red_sandstone", "polished_andesite", "andesite", "diorite", "polished_diorite", "granite", "polished_granite" } },
            { "stone_slab_type_4", new object[] { "mossy_stone_brick", "smooth_quartz", "stone", "cut_sandstone", "cut_red_sandstone" } },
            { "stone_type", new object[] { "stone", "granite", "granite_smooth", "diorite", "diorite_smooth", "andesite", "andesite_smooth" } },
            { "stripped_bit", new object[] { (byte)0, (byte)1 } },
            { "structure_block_type", new object[] { "data", "save", "load", "corner", "invalid", "export" } },
            { "structure_void_type", new object[] { "void", "air" } },
            { "suspended_bit", new object[] { (byte)0, (byte)1 } },
            { "tall_grass_type", new object[] { "default", "tall", "fern", "snow" } },
            { "tip", new object[] { (byte)0, (byte)1 } },
            { "toggle_bit", new object[] { (byte)0, (byte)1 } },
            { "top_slot_bit", new object[] { (byte)0, (byte)1 } },
            { "torch_facing_direction", new object[] { "unknown", "west", "east", "north", "south", "top" } },
            { "trial_spawner_state", new object[] { 0, 1, 2, 3, 4, 5 } },
            { "triggered_bit", new object[] { (byte)0, (byte)1 } },
            { "turtle_egg_count", new object[] { "one_egg", "two_egg", "three_egg", "four_egg" } },
            { "twisting_vines_age", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 } },
            { "update_bit", new object[] { (byte)0, (byte)1 } },
            { "upper_block_bit", new object[] { (byte)0, (byte)1 } },
            { "upside_down_bit", new object[] { (byte)0, (byte)1 } },
            { "vault_state", new object[] { "inactive", "active", "unlocking", "ejecting" } },
            { "vine_direction_bits", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
            { "wall_block_type", new object[] { "cobblestone", "mossy_cobblestone", "granite", "diorite", "andesite", "sandstone", "brick", "stone_brick", "mossy_stone_brick", "nether_brick", "end_brick", "prismarine", "red_sandstone", "red_nether_brick" } },
            { "wall_connection_type_east", new object[] { "none", "short", "tall" } },
            { "wall_connection_type_north", new object[] { "none", "short", "tall" } },
            { "wall_connection_type_south", new object[] { "none", "short", "tall" } },
            { "wall_connection_type_west", new object[] { "none", "short", "tall" } },
            { "wall_post_bit", new object[] { (byte)0, (byte)1 } },
            { "weeping_vines_age", new object[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 } },
            { "weirdo_direction", new object[] { 0, 1, 2, 3 } },
            { "wood_type", new object[] { "oak", "spruce", "birch", "jungle", "acacia", "dark_oak" } },
        };
    }
}
