namespace DaemonMC.Network.Enumerations
{
    public enum PersonaPieceTypes
    {
        persona_skeleton,
        persona_body,
        persona_skin,
        persona_bottom,
        persona_feet,
        persona_dress,
        persona_top,
        persona_high_pants,
        persona_hand,
        persona_outerwear,
        persona_facial_hair,
        persona_mouth,
        persona_eyes,
        persona_hair,
        persona_hood,
        persona_back,
        persona_face_accessory,
        persona_head,
        persona_legs,
        persona_left_leg,
        persona_right_leg,
        persona_arms,
        persona_left_arm,
        persona_right_arm,
        persona_capes,
        persona_classic_Skin,
        persona_emote,
    };
}
