name: .NET

on:
  push:
    branches: [ "release" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Extract version from .csproj
      run: |
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" DaemonMC/DaemonMC.csproj)
        echo "VERSION=$version" >> $GITHUB_ENV
        
    - name: Create Git Tag
      run: |
        VERSION=${{ env.VERSION }}
        git tag $VERSION
        git push origin $VERSION
        
    - name: Read releasenotes
      run: |
        description=$(head -n 10 releasenotes.txt)
        echo "DESCRIPTION=$description" >> $GITHUB_ENV
        
    - name: Restore dependencies
      working-directory: DaemonMC
      run: dotnet restore
      
    - name: Build
      working-directory: DaemonMC
      run: dotnet build --no-restore
      
    - name: Publish Application
      working-directory: DaemonMC
      run: dotnet publish -c Release --no-restore -o DaemonMC
      
    - name: Zip Published Application
      working-directory: DaemonMC
      run: zip -r DaemonMC.zip DaemonMC/
      
    - name: Publish NuGet Package
      working-directory: DaemonMC
      run: |
        dotnet nuget push bin/Release/*.nupkg \
        --api-key ${{ secrets.nugetkey }} \
        --source https://api.nuget.org/v3/index.json \
        --skip-duplicate
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: "DaemonMC ${{ env.VERSION }}"
        body: ${{ env.DESCRIPTION }}
        files: DaemonMC/DaemonMC.zip
      env:
        GITHUB_TOKEN: ${{ secrets.actionpat }}