name: .NET

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Application
      run: dotnet publish -c Release -o out
    - name: Zip Published Application
      run: zip -r DaemonMC.zip out/
    - name: Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: DaemonMC.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
